In [1721]:
import pandas as pd
df = pd.read_csv('data.csv')
df.head()

,patient_id,admission_date,season,age,gender,region,primary_diagnosis,comorbidities_count,length_of_stay,treatment_type,medications_count,followup_visits_last_year,prev_readmissions,insurance_type,discharge_disposition,readmission_risk_score,label
0,P00001,2022-04-14,Spring,66,Male,South,Diabetes,5,6,Interventional,8,6,1,Medicare,Home Health,0.92,1
1,P00002,2021-09-19,Fall,55,Male,South,Diabetes,4,6,Interventional,6,4,3,Private,Home Health,0.88,1
2,P00003,2023-04-12,Spring,69,Female,West,Hypertension,6,8,Medical,9,6,2,Medicare,Skilled Nursing,0.97,1
3,P00004,2023-08-14,Summer,83,Male,South,Stroke,6,11,Medical,11,4,2,Medicare,Skilled Nursing,0.97,1
4,P00005,2021-11-05,Fall,54,Female,North,Stroke,4,10,Medical,6,2,1,Uninsured,Home Health,0.83,1

In [1722]:
readmit_values = df['prev_readmissions'].value_counts()
readmit_means = df.groupby('prev_readmissions')['label'].mean()

def readmit_groups(x):
    if x == 0:
        return 0
    elif x == 1:
        return 1
    else:
        return 2
    
groups = df['prev_readmissions'].map(readmit_groups)
df['prev_readmit_group'] = groups

In [1723]:
df.groupby('comorbidities_count')['label'].agg(['count', 'mean'])

def comorbidities_groups(x):
    if x == 1:
        return 'one'
    elif x == 2:
        return 'two'
    elif x == 3:
        return 'three'
    elif x == 4:
        return 'four'
    else:
        return 'five or more'

groups = df['comorbidities_count'].map(comorbidities_groups)
df['comorbidities_group'] = groups

In [1724]:
df.groupby('length_of_stay')['label'].agg(['count', 'mean'])

                count      mean
length_of_stay
3                  14  0.142857
4                 166  0.415663
5                 764  0.645288
6                1342  0.702683
7                1410  0.733333
8                1453  0.783207
9                1287  0.856255
10                867  0.885813
11                465  0.916129
12                163  0.901840
13                 52  0.884615
14                 14  0.928571
15                  3  0.666667

In [1725]:
df['los_group'] = df['length_of_stay'].map({
    3:'3 to 4',
    4: '3 to 4',
    5: '5',
    6: '6 to 8',
    7: '6 to 8',
    8: '6 to 8',
    }).fillna('9+')
df.groupby('los_group')['label'].agg(['count', 'mean'])

# 6, 7, 8

           count      mean
los_group
3 to 4       180  0.394444
5            764  0.645288
6 to 8      4205  0.740785
9+          2851  0.878288

In [1726]:
df['medications_group'] = df['medications_count'].replace({
    **{k: '8 to 14' for k in [8, 9, 10, 11, 12, 13, 14]},
    **{j: '15+' for j in [15, 16, 17, 18]}
})

df.groupby('medications_group')['label'].agg(['count', 'mean'])

                   count      mean
medications_group
2                     76  0.223684
3                    195  0.394872
4                    776  0.563144
5                    104  0.365385
6                   1767  0.658744
7                    883  0.721404
15+                    8  1.000000
8 to 14             4191  0.907898

In [1727]:
df.groupby('followup_visits_last_year')['label'].agg(['count', 'mean'])

                           count      mean
followup_visits_last_year
0                             41  0.146341
1                            205  0.404878
2                           2469  0.648846
3                            992  0.726815
4                           2307  0.832250
5                            663  0.903469
6                           1013  0.941757
7                            144  0.944444
8                            144  0.972222
9                             15  1.000000
10                             7  1.000000

In [1728]:
df['followup_visits_group'] = df['followup_visits_last_year'].replace({
    0: '0 to 1',
    1: '0 to 1',
    2: '2',
    3: '3',
    4: '4',
    5: '5 or more',
    6: '5 or more',
    7: '5 or more',
    8: '5 or more',
    9: '5 or more',
    10: '5 or more',
})

In [1729]:
agg = df.groupby('followup_visits_group')['label'].agg(['count', 'mean'])
agg

                       count      mean
followup_visits_group
0 to 1                   246  0.361789
2                       2469  0.648846
3                        992  0.726815
4                       2307  0.832250
5 or more               1986  0.932024

In [1730]:
df.head()

,patient_id,admission_date,season,age,gender,region,primary_diagnosis,comorbidities_count,length_of_stay,treatment_type,...,prev_readmissions,insurance_type,discharge_disposition,readmission_risk_score,label,prev_readmit_group,comorbidities_group,los_group,medications_group,followup_visits_group
0,P00001,2022-04-14,Spring,66,Male,South,Diabetes,5,6,Interventional,...,1,Medicare,Home Health,0.92,1,1,five or more,6 to 8,8 to 14,5 or more
1,P00002,2021-09-19,Fall,55,Male,South,Diabetes,4,6,Interventional,...,3,Private,Home Health,0.88,1,2,four,6 to 8,6,4
2,P00003,2023-04-12,Spring,69,Female,West,Hypertension,6,8,Medical,...,2,Medicare,Skilled Nursing,0.97,1,2,five or more,6 to 8,8 to 14,5 or more
3,P00004,2023-08-14,Summer,83,Male,South,Stroke,6,11,Medical,...,2,Medicare,Skilled Nursing,0.97,1,2,five or more,9+,8 to 14,4
4,P00005,2021-11-05,Fall,54,Female,North,Stroke,4,10,Medical,...,1,Uninsured,Home Health,0.83,1,1,four,9+,6,2

In [1731]:
df.groupby('season')['label'].agg(['count', 'mean'])

        count      mean
season
Fall     1996  0.757014
Spring   1972  0.763185
Summer   1991  0.763435
Winter   2041  0.806957

In [1732]:
df.groupby('gender')['label'].mean()

gender
Female    0.778920
Male      0.766247
Name: label, dtype: float64

In [1733]:
dates = df['admission_date'].value_counts()
dates.describe()

count    1092.000000
mean        7.326007
std         2.739189
min         1.000000
25%         5.000000
50%         7.000000
75%         9.000000
max        16.000000
Name: count, dtype: float64

In [1734]:
df['admission_date'] = pd.to_datetime(df['admission_date'], errors='coerce')
df['admission_month'] = df['admission_date'].dt.month
df['admission_year'] = df['admission_date'].dt.year

In [1735]:
df.head()

,patient_id,admission_date,season,age,gender,region,primary_diagnosis,comorbidities_count,length_of_stay,treatment_type,...,discharge_disposition,readmission_risk_score,label,prev_readmit_group,comorbidities_group,los_group,medications_group,followup_visits_group,admission_month,admission_year
0,P00001,2022-04-14,Spring,66,Male,South,Diabetes,5,6,Interventional,...,Home Health,0.92,1,1,five or more,6 to 8,8 to 14,5 or more,4,2022
1,P00002,2021-09-19,Fall,55,Male,South,Diabetes,4,6,Interventional,...,Home Health,0.88,1,2,four,6 to 8,6,4,9,2021
2,P00003,2023-04-12,Spring,69,Female,West,Hypertension,6,8,Medical,...,Skilled Nursing,0.97,1,2,five or more,6 to 8,8 to 14,5 or more,4,2023
3,P00004,2023-08-14,Summer,83,Male,South,Stroke,6,11,Medical,...,Skilled Nursing,0.97,1,2,five or more,9+,8 to 14,4,8,2023
4,P00005,2021-11-05,Fall,54,Female,North,Stroke,4,10,Medical,...,Home Health,0.83,1,1,four,9+,6,2,11,2021

In [1736]:
df.groupby('admission_year')['label'].agg(['count', 'mean'])

                count      mean
admission_year
2021             2717  0.784689
2022             2664  0.769144
2023             2619  0.764414

In [1737]:
months = df.groupby('admission_month')['label'].agg(['count', 'mean'])
months.describe()

            count       mean
count   12.000000  12.000000
mean   666.666667   0.772570
std     28.566775   0.023200
min    624.000000   0.737609
25%    647.000000   0.757515
50%    664.000000   0.767037
75%    686.500000   0.782065
max    715.000000   0.813986

In [1738]:
means = df.groupby('admission_month')['label'].mean()
means

admission_month
1     0.804843
2     0.801282
3     0.775602
4     0.760542
5     0.753106
6     0.770992
7     0.763081
8     0.756173
9     0.737609
10    0.757962
11    0.775660
12    0.813986
Name: label, dtype: float64

In [1739]:
df['admission_day'] = df['admission_date'].dt.day
overview = df.groupby('admission_day')['label'].agg(['count','mean'])
overview.describe()
overview.mean()

count    258.064516
mean       0.773307
dtype: float64

In [1740]:
overall = df['label'].mean()
lower = overall - 0.05
upper = overall + 0.05
day_means = df.groupby('admission_day')['label'].mean()

In [1741]:
day_means[day_means <= lower]

Series([], Name: label, dtype: float64)

In [1742]:
high_outlier = day_means[day_means >= upper]
high_outlier

admission_day
23    0.829181
Name: label, dtype: float64

In [1743]:
high_outlier.value_counts()

label
0.829181    1
Name: count, dtype: int64

In [1744]:
df['days_of_week'] = df['admission_date'].dt.day_name()
days_overview = df.groupby('days_of_week')['label'].mean()
days_overview.describe()

count    7.000000
mean     0.773239
std      0.011933
min      0.758143
25%      0.766118
50%      0.770959
75%      0.779606
max      0.792125
Name: label, dtype: float64

In [1745]:
overall = df['label'].mean()
lower = overall - 0.05
upper = overall + 0.05
low_outliers = days_overview[days_overview <= lower]
high_outliers = days_overview[days_overview >= upper]

In [1746]:
print('low:')
print(low_outliers)
print('high')
print(high_outliers)

low:
Series([], Name: label, dtype: float64)
high
Series([], Name: label, dtype: float64)

In [1747]:
df.head()

,patient_id,admission_date,season,age,gender,region,primary_diagnosis,comorbidities_count,length_of_stay,treatment_type,...,label,prev_readmit_group,comorbidities_group,los_group,medications_group,followup_visits_group,admission_month,admission_year,admission_day,days_of_week
0,P00001,2022-04-14,Spring,66,Male,South,Diabetes,5,6,Interventional,...,1,1,five or more,6 to 8,8 to 14,5 or more,4,2022,14,Thursday
1,P00002,2021-09-19,Fall,55,Male,South,Diabetes,4,6,Interventional,...,1,2,four,6 to 8,6,4,9,2021,19,Sunday
2,P00003,2023-04-12,Spring,69,Female,West,Hypertension,6,8,Medical,...,1,2,five or more,6 to 8,8 to 14,5 or more,4,2023,12,Wednesday
3,P00004,2023-08-14,Summer,83,Male,South,Stroke,6,11,Medical,...,1,2,five or more,9+,8 to 14,4,8,2023,14,Monday
4,P00005,2021-11-05,Fall,54,Female,North,Stroke,4,10,Medical,...,1,1,four,9+,6,2,11,2021,5,Friday

In [1748]:
# need to drop non significant columns: admission date, year, month, day of week, date, season... also drop gender
df2 = df.copy()
df2 = df2.drop(columns=['admission_date', 'season', 'gender', 'admission_month', 'admission_year', 'admission_day', 'days_of_week'])
df2.head()

,patient_id,age,region,primary_diagnosis,comorbidities_count,length_of_stay,treatment_type,medications_count,followup_visits_last_year,prev_readmissions,insurance_type,discharge_disposition,readmission_risk_score,label,prev_readmit_group,comorbidities_group,los_group,medications_group,followup_visits_group
0,P00001,66,South,Diabetes,5,6,Interventional,8,6,1,Medicare,Home Health,0.92,1,1,five or more,6 to 8,8 to 14,5 or more
1,P00002,55,South,Diabetes,4,6,Interventional,6,4,3,Private,Home Health,0.88,1,2,four,6 to 8,6,4
2,P00003,69,West,Hypertension,6,8,Medical,9,6,2,Medicare,Skilled Nursing,0.97,1,2,five or more,6 to 8,8 to 14,5 or more
3,P00004,83,South,Stroke,6,11,Medical,11,4,2,Medicare,Skilled Nursing,0.97,1,2,five or more,9+,8 to 14,4
4,P00005,54,North,Stroke,4,10,Medical,6,2,1,Uninsured,Home Health,0.83,1,1,four,9+,6,2

In [1749]:
df2 = df2.drop(columns=['patient_id', 'comorbidities_count', 'length_of_stay', 'medications_count', 'followup_visits_last_year', 'prev_readmissions'])

In [1750]:
df2.head()

,age,region,primary_diagnosis,treatment_type,insurance_type,discharge_disposition,readmission_risk_score,label,prev_readmit_group,comorbidities_group,los_group,medications_group,followup_visits_group
0,66,South,Diabetes,Interventional,Medicare,Home Health,0.92,1,1,five or more,6 to 8,8 to 14,5 or more
1,55,South,Diabetes,Interventional,Private,Home Health,0.88,1,2,four,6 to 8,6,4
2,69,West,Hypertension,Medical,Medicare,Skilled Nursing,0.97,1,2,five or more,6 to 8,8 to 14,5 or more
3,83,South,Stroke,Medical,Medicare,Skilled Nursing,0.97,1,2,five or more,9+,8 to 14,4
4,54,North,Stroke,Medical,Uninsured,Home Health,0.83,1,1,four,9+,6,2

In [1751]:
df2.to_pickle('cleaned_one.pkl')